### ISSUE TITLE
Minor cosmetic issues

### ISSUE THREAD

**Issue by jeff-yin** [ansible-collections/dellemc.enterprise_sonic#109]
1. In changelogs/.plugin-cache.yaml:

```
  sonic_command:
      description: Runs commands on devices running Enterprise SONiC
      name: sonic_command
      namespace: ''
      version_added: 1.0.0
```
Clarify what "commands" means -- are these "exec mode CLI commands?"

```
    sonic_config:
      description: Manages configuration sections on devices running Enterprise SONiC
      name: sonic_config
      namespace: ''
      version_added: 1.0.0
```

Clarify what "configuration sections" means. Are these "config mode CLI commands?"

 2. plugins/cliconf/sonic.py makes a reference to OS10, which is incorrect.
