### ISSUE TITLE
[BUG]: sonic_l2_interfaces VLAN configuration expects int

### ISSUE THREAD

**Issue by chumbri** [ansible-collections/dellemc.enterprise_sonic#168]
### Bug Description

Hi,

I tried to run your sample playbook: `sonic_resource_modules.yaml`, more specific the following section:

```
- name: Configure Layer 2 interfaces
     dellemc.enterprise_sonic.sonic_l2_interfaces:
        config:
        - name: Eth1/2
          access:
            vlan: 701
          trunk:
            allowed_vlans:
              - vlan: 702
              - vlan: 703
        state: merged
     register: sonic_l2_interfaces_output
```

The above section fails with the following error message:

`"msg": "argument vlan is of type <class 'str'> found in 'config -> trunk -> allowed_vlans'. and we were unable to convert to int: <class 'str'> cannot be converted to an int"`

### Product Name

Dell Enterprise SONIC

### Component or Module Name

httpapi

### DellEMC Enterprise SONiC Ansible Collection Version

dellemc.enterprise_sonic 2.0.0

### SONiC Software Version

4.0.3-Enterprise_Base

### Configuration

```
ansible 2.10.8
executable location = /usr/bin/ansible
python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
```

### Steps to Reproduce

1. Get Ubuntu 22.04
2. Install Ansible 2.10.8
3. Install Dependencies
```
pip3 install paramiko>=2.7
pip3 install jinja2>=2.8
pip3 install ansible-base
ansible-galaxy collection install dellemc.enterprise_sonic
```
4. Create sample structure:
```
sonic_resource_modules.yaml
host_vars/sonic_sw1.yaml
inventory.ini
```
5. Run Playbook
```
ANSIBLE_NETWORK_GROUP_MODULES=sonic ansible-playbook sonic_resource_modules.yaml -i inventory.ini
```

NOTE: Ansible Playbook was run against an official GNS3 Enterprise SONIC 4.0.3 switch image

### Expected Behavior

Eth1/2 is properly configured with access vlan 701 and tagged vlans 702 and 703

### Actual Behavior

```
TASK [Configure Layer 2 interfaces] **********************************************************************************************************************************
fatal: [sonic_sw1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config": [
                {
                    "access": {
                        "vlan": 100
                    },
                    "name": "Eth1/1",
                    "trunk": null
                },
                {
                    "access": {
                        "vlan": 701
                    },
                    "name": "Eth1/2",
                    "trunk": {
                        "allowed_vlans": [
                            {
                                "vlan": "702..703"
                            }
                        ]
                    }
                }
            ],
            "state": "merged"
        }
    },
    "msg": "argument vlan is of type <class 'str'> found in 'config -> trunk -> allowed_vlans'. and we were unable to convert to int: <class 'str'> cannot be converted to an int"
}

```

### Logs

`host_vars/sonic_sw1.yaml`
```
hostname: sonic_sw1

# Common parameters for connection type httpapi or network_cli:
ansible_user: xxx
ansible_pass: xxx
ansible_network_os: dellemc.enterprise_sonic.sonic

# Additional parameters for connection type httpapi:
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
```

`inventory.ini`
```
[sonic_sw1]
sonic_sw1 ansible_host=xxx

[sonic_sw2]
sonic_sw2 ansible_host=xxx

[sonic_switches:children]
sonic_sw1
sonic_sw2
```

`sonic_resource_modules.yaml`
```
---
- name: VLANs, Layer 2 and Layer 3 interfaces configuration using Enterprise SONiC resource modules
  hosts: sonic_sw1
  gather_facts: yes
  connection: httpapi
  tasks:
   - name: Configure VLANs
     dellemc.enterprise_sonic.sonic_vlans:
        config:
         - vlan_id: 701
         - vlan_id: 702
         - vlan_id: 703
         - vlan_id: 704
        state: merged
     register: sonic_vlans_output
   - name: Configure Layer 2 interfaces
     dellemc.enterprise_sonic.sonic_l2_interfaces:
        config:
        - name: Eth1/2
          access:
            vlan: 701
          trunk:
            allowed_vlans:
              - vlan: 702
              - vlan: 703
        state: merged
     register: sonic_l2_interfaces_output
   - name: Configure Layer 3 interfaces
     dellemc.enterprise_sonic.sonic_l3_interfaces:
       config:
        - name: Eth1/3
          ipv4:
            addresses:
              - address: 8.1.1.1/16
       state: merged
     register: sonic_l3_interfaces_output
```
