### ISSUE TITLE
[QUESTION]: Replacing LAG interface with L2, and vice versa

### ISSUE THREAD

**Issue by fzakfeld** [ansible-collections/dellemc.enterprise_sonic#278]
### How can the team help?

We need to change some interfaces from being a LAG member to being a standalone L2 port, and vice versa. Problem is that the LAG can not be configured at physical interface level, but rather the interfaces need to be configured as a 'member' on the LAG interface using sonic_lag_interfaces.

Since configuring L2 and LAG interfaces are different tasks, one is executed at first. If the L2 interfaces are configured first, then there might still be a port-channel configured on a port making the config task fail.

Is there any recommended way of handling this?

**Details: ?**

Our task looks like this:

```
- name: Set LAG Interfaces
  dellemc.enterprise_sonic.sonic_lag_interfaces:
    config: "{{ switch_ports | scaleup_sonic_lacp_interfaces }}"
    state: replaced

- name: Configure L2 Interfaces
  dellemc.enterprise_sonic.sonic_l2_interfaces:
    config: "{{ switch_ports | scaleup_sonic_l2_interfaces }}"
    state: replaced
```

`switch_ports | scaleup_sonic_lacp_interfaces` will return a list of LAG interfaces, in this case including one with Ethernet124 as the member.

`switch_ports | scaleup_sonic_l2_interfaces` will return a list of all L2 interfaces, without Ethernet124 (prior configured as L2 interface)

```
interface Ethernet124
 mtu 9100
 speed 100000
 unreliable-los auto
 no shutdown
 switchport access Vlan 1
 switchport trunk allowed Vlan 100
!
```

Task runs:

```
fatal: [redacted]: FAILED! => {
    "changed": false,
    "code": -32603,
    "invocation": {
        "module_args": {
            "config": [
                (redacted)
            ],
            "state": "replaced"
        }
    },
    "msg": "{'ietf-restconf:errors': {'error': [{'error-type': 'application', 'error-tag': 'invalid-value', 'error-app-tag': 'Config Validation Error', 'error-message': 'PortChannel configuration not allowed. Access VLAN:1 configuration exists on interface Ethernet124.', 'error-info': {'cvl-error': {'error-code': 1002, 'table-name': 'PORTCHANNEL_MEMBER', 'key-values': ['PORTCHANNEL_MEMBER', 'PortChannel255', 'Ethernet124']}}}]}, 'code': 400, 'request_data': {'path': 'data/openconfig-interfaces:interfaces/interface=Ethernet124/openconfig-if-ethernet:ethernet/config/openconfig-if-aggregate:aggregate-id', 'method': 'patch'}}"
}
```
