### ISSUE TITLE
Feature Request: Add external-ip option to dellemc.enterprise_sonic.sonic_vxlans module

### ISSUE THREAD

**Issue by dataolle** [ansible-collections/dellemc.enterprise_sonic#327]
I propose adding an external-ip option to the dellemc.enterprise_sonic.sonic_vxlans module. Currently, this option is not available in the resource module, which limits its functionality compared to what is possible through sonic-cli on the device.

The implementation should allow users to specify an external-ip in the module configuration, functioning similarly to other existing options like source-ip and primary-ip.

Example Usage:

Before State Configuration:

```
# Running configuration before applying changes
# ...
#interface vxlan vteptest1
# source-ip 1.1.1.1
# primary-ip 2.2.2.2
# ...
```
Ansible Playbook Snippet:

```yaml
- name: "Configure vxlan with external IP"
  dellemc.enterprise_sonic.sonic_vxlans:
    config:
      - name: vteptest2
        source_ip: 3.3.3.3
        primary_ip: 4.4.4.4
        external_ip: 5.5.5.5
        # Additional configuration
    state: overridden
```

After State Configuration:

```
# Expected running configuration after applying changes
# ...
#interface vxlan vteptest2
# source-ip 3.3.3.3
# primary-ip 4.4.4.4
# external-ip 5.5.5.5
# ...
```
Alternatives Considered:
None. The rationale for this feature is to align the module's capabilities with the configuration options available in sonic-cli, ensuring consistency and full utilization of the device's features.
