### ISSUE TITLE
Getting error while making interfaces up or down using module dellemc.enterprise_sonic.sonic_interfaces:  {"changed": false, "code": -32603, "msg": "'command'"}

### ISSUE THREAD

**Issue by shoneslab** [ansible-collections/dellemc.enterprise_sonic#397]
### Bug Description

I am trying make the sonic ethernet interfaces interfaces up/down using the module and getting the error:

Playbook
```
---
- name: Manage Sonic Switch Interfaces
  hosts: vault_cleanroom_switches
  gather_facts: no
  collections:
    - dellemc.enterprise_sonic

  tasks:
     - name: Set interface down
      dellemc.enterprise_sonic.sonic_interfaces:
        config:
          - name: Ethernet12
            enabled: True
        state: replaced
```

Inventory File

```
all:
  children:
    vault_cleanroom_switches:
      hosts:
        sonic_switch_01:
          ansible_host: 192.168.60.2
          ansible_user: admin
          ansible_password: YourPaSsWoRd
          ansible_connection: network_cli
          ansible_network_os: dellemc.enterprise_sonic.sonic
```

### Product Name

Dell Enterprise Sonic Ansible Module

### Component or Module Name

dellemc.enterprise_sonic.sonic_interfaces

### DellEMC Enterprise SONiC Ansible Collection Version

v2.4.0

### SONiC Software Version

Enterprise Sonic 4.2.1 on GNS3 2.2.47

### Configuration

**ansible version**
```
ansible [core 2.17.0]
  config file = /opt/automation/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections:/opt/automation/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Apr 18 2024, 07:52:31) [GCC 13.2.1 20240309] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Steps to Reproduce

Execute the playbook.

### Expected Behavior

Playbook should exit successfully by making the interface enabled with status up

### Actual Behavior

```
TASK [Set interface down] ****************************************************************************************************************************************
fatal: [sonic_switch_01]: FAILED! => {"changed": false, "code": -32603, "msg": "'command'"}

```

### Logs

```
ansible-playbook -i inventory/ playbooks/airgap-management.yml 

PLAY [Manage Sonic Switch Interfaces] ****************************************************************************************************************************

TASK [Set interface down] ****************************************************************************************************************************************
fatal: [sonic_switch_01]: FAILED! => {"changed": false, "code": -32603, "msg": "'command'"}

PLAY RECAP *******************************************************************************************************************************************************
sonic_switch_01            : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```
