### ISSUE TITLE
[BUG]: Cannot set MSTP instance 0 priority without defining spanning tree 0 explicitly.

### ISSUE THREAD

**Issue by TafkaMax** [ansible-collections/dellemc.enterprise_sonic#472]
### Bug Description

Cannot set MST instance 0 priority without defining the MST instance explicitly. As you can see from the logs, the MST instance 0 is not found. Although it exists always implicitly and is a special type of mst instance.

 I cannot even set the mst instance 0 config via cli.

```
core-01(config)# spanning-tree mst configuration 
core-01(config-mst)# instance 0 Vlan 1-19,24-68,73-77,79-89,93-2999,3001-4094
core-01(config-mst)# end
sw-trt-int-core-01# show running-configuration spanning-tree 
spanning-tree mode mst
spanning-tree edge-port bpdufilter default
spanning-tree loopguard default
spanning-tree mst 1-3,15 priority 4096
!
spanning-tree mst configuration
 name test
 revision 1
 instance 1 vlan 20,90
 instance 2 vlan 22,70,72,91
 instance 3 vlan 21,23,69,71,78,92
 instance 15 vlan 3000
 activate
```
As you can see, because MST instance 0 has a special role in mstp specification, then it also is not added to the configuration. As it is implicitliy the sum of all of the VLAN-s not specified to any of the other MST instances.

After running this command the `config_db.json` file was modified as such and the new `"0": {}` was created, but the configuration is empty. 

```json
    "STP_MST_INST": {
        "0": {},
        "1": {
            "bridge_priority": "4096",
            "vlan": [
                "20",
                "90"
            ]
        },
        "2": {
            "bridge_priority": "4096",
            "vlan": [
                "22",
                "70",
                "72",
                "91"
            ]
        },
        "3": {
            "bridge_priority": "4096",
            "vlan": [
                "21",
                "23",
                "69",
                "71",
                "78",
                "92"
            ]
        },
        "15": {
            "bridge_priority": "4096",
            "vlan": [
                "3000"
            ]
        }
    },

```

This thing with setting the VLAN-s for MST 0 manually is actually not part of the problem, but it illustrates that the VLAN-s that the user specifies should be ignored, which they are, but allowing to set the bridge_prio via the ansible should still be doable.

Now when I wish to add the `bridge_priority` to the `mst_id: 0` via the ansible STP module then the following error happens as shown in the Log below in the Logs section.

### Product Name

Dell Enteprise Sonic

### Component or Module Name

httpapi

### DellEMC Enterprise SONiC Ansible Collection Version

latest

### SONiC Software Version

4.4.0

### Configuration

```
CONFIG_FILE() = /home/tansper/ansible/ansible.cfg
DEFAULT_HOST_LIST(/home/tansper/ansible/ansible.cfg) = ['/home/tansper/ansible/hosts']
DEFAULT_LOOKUP_PLUGIN_PATH(/home/tansper/ansible/ansible.cfg) = ['/home/tansper/ansible/plugins/lookup']
DEFAULT_VAULT_PASSWORD_FILE(/home/tansper/ansible/ansible.cfg) = /home/tansper/ansible/scripts/vault_password.sh
EDITOR(env: EDITOR) = vim
HOST_KEY_CHECKING(/home/tansper/ansible/ansible.cfg) = False
PAGER(env: PAGER) = less
```

### Steps to Reproduce

```yaml
- name: SONiC STP
  dellemc.enterprise_sonic.sonic_stp:
    config:
      global:
        bridge_priority: 4096
        enabled_protocol: mst
      mstp:
        mst_name: test
        revision: 1
        mst_instances:
          - mst_id: 0 # <---- this is the faulty place
            bridge_priority: 4096 # <---- this is the faulty place
          - mst_id: 1
            bridge_priority: 4096
            vlans:
              - '20'
              - '90'
          - mst_id: 2
            bridge_priority: 4096
            vlans:
              - '22'
              - '70'
              - '72'
              - '91'
          - mst_id: 3
            bridge_priority: 4096
            vlans:
              - '21'
              - '23'
              - '69'
              - '71'
              - '78'
              - '92'
          - mst_id: 15
            bridge_priority: 4096
            vlans:
              - '3000'
```

```
show running-configuration spanning-tree 
spanning-tree mode mst
spanning-tree edge-port bpdufilter default
spanning-tree loopguard default
spanning-tree mst 0-3,15 priority 4096
!
spanning-tree mst configuration
 name redacted
 revision 1
 instance 1 vlan 20,90
 instance 2 vlan 22,70,72,91
 instance 3 vlan 21,23,69,71,78,92
 instance 15 vlan 3000
 activate
```

### Expected Behavior

The Ansible module works.

### Actual Behavior

It errors out not finding mst instance with ID 0.

Also I can not add the mstp instance 0 via the CLI as it is implicit.

### Logs

```
                "mstp": {
                    "fwd_delay": null,
                    "hello_time": null,
                    "max_age": null,
                    "max_hop": null,
                    "mst_instances": [
                        {
                            "bridge_priority": 4096,
                            "interfaces": null,
                            "mst_id": null,
                            "vlans": null
                        },
                        {
                            "bridge_priority": 4096,
                            "interfaces": null,
                            "mst_id": 1,
                            "vlans": [
                                "20",
                                "90"
                            ]
                        },
                        {
                            "bridge_priority": 4096,
                            "interfaces": null,
                            "mst_id": 2,
                            "vlans": [
                                "22",
                                "70",
                                "72",
                                "91"
                            ]
                        },
                        {
                            "bridge_priority": 4096,
                            "interfaces": null,
                            "mst_id": 3,
                            "vlans": [
                                "21",
                                "23",
                                "69",
                                "71",
                                "78",
                                "92"
                            ]
                        },
                        {
                            "bridge_priority": 4096,
                            "interfaces": null,
                            "mst_id": 15,
                            "vlans": [
                                "3000"
                            ]
                        }
                    ],
                    "mst_name": "redacted",
                    "revision": 1
                },
                "pvst": null,
                "rapid_pvst": null
            },
            "state": "merged"
        }
    },
    "msg": "missing required arguments: mst_id found in config -> mstp -> mst_instances"
}
```
