### ISSUE TITLE
[QUESTION]:(Error)Is socket_path a required parameter for the sonic_api module? If so, how should it be set?

### ISSUE THREAD

**Issue by DelDex** [ansible-collections/dellemc.enterprise_sonic#488]
Playbook Example
This is the task I ran:
- name: Add VLAN network instance
  dellemc.enterprise_sonic.sonic_api:
    method: PUT
    endpoint: "/rest/v1.0/vlan"
    data:
      vlan_id: 10
      description: "Test VLAN"

What I Expect
The VLAN should be added to the device without errors, and the API should return a success status.

What Happens
The task fails with the following error:

msg: socket_path must be a value

Questions

1)Is socket_path a required parameter for the sonic_api module? If so, how should it be set?
2)The documentation does not mention socket_path. Could you clarify its purpose and provide guidance on how to use it correctly?
3)Is there a default value for socket_path, or does it need to be manually specified?

Troubleshooting Steps Tried

Checked the module documentation but found no mention of socket_path.
Added socket_path: "/var/run/sonic/api.sock" explicitly, but I'm unsure if this is the correct value for my setup.

**Comment by ArunSaravananBalachandran** [comment]
The ansible connection type determines the value of 'socket_path'.

Depending on the module being used, the ansible connection type can either be 'network_cli' (for CLI commands) or 'httpapi'.
Hence, for sonic_api the connection type is 'httpapi'.

Example:
```
---
- hosts: device1
  connection: httpapi
  tasks:
    - name: sonic_api example
      dellemc.enterprise_sonic.sonic_api:
        url: "data/openconfig-network-instance:network-instances/network-instance=Vlan100"
        method: "GET"
        status_code: 200
```
