### ISSUE TITLE
[BUG]: sonic_stp mstp adding a vlan to a an mst instance removes all previously defined vlans from that instance 

### ISSUE THREAD

**Issue by TafkaMax** [ansible-collections/dellemc.enterprise_sonic#502]
### Bug Description

When adding a new vlan to an MST instance the previously defined vlans are removed from the mst instance. 

```
- name: Merge STP configuration for Dell Sonic
  dellemc.enterprise_sonic.sonic_stp:
    config: '{{ sonic__stp }}'
    state: replaced
```

The output of the sonic_stp variable is below.

```
ok: [redacted] => {
    "sonic__stp": {
        "global": {
            "bpdu_filter": true,
            "bridge_priority": 4096,
            "enabled_protocol": "mst",
            "loop_guard": true
        },
        "mstp": {
            "mst_instances": [
                {
                    "bridge_priority": 4096,
                    "mst_id": 0
                },
                {
                    "bridge_priority": 4096,
                    "mst_id": 1,
                    "vlans": [
                        "20",
                        "90"
                    ]
                },
                {
                    "bridge_priority": 4096,
                    "mst_id": 2,
                    "vlans": [
                        "14",
                        "22",
                        "70",
                        "72",
                        "91"
                    ]
                },
                {
                    "bridge_priority": 4096,
                    "mst_id": 3,
                    "vlans": [
                        "21",
                        "23",
                        "69",
                        "71",
                        "78",
                        "92"
                    ]
                },
                {
                    "bridge_priority": 4096,
                    "mst_id": 15,
                    "vlans": [
                        "3000"
                    ]
                }
            ],
            "mst_name": "redacted",
            "revision": 12
        }
    }
}
```

### Product Name

Dell Enterprise Sonic

### Component or Module Name

httpapi

### DellEMC Enterprise SONiC Ansible Collection Version

latest git hash

### SONiC Software Version

4.4.1-Enterprise_Standard

### Configuration

```
CONFIG_FILE() = /home/tansper/ansible/ansible.cfg
DEFAULT_HOST_LIST(/home/tansper/ansible/ansible.cfg) = ['/home/tansper/ansible/hosts']
DEFAULT_LOOKUP_PLUGIN_PATH(/home/tansper/ansible/ansible.cfg) = ['/home/tansper/ansible/plugins/lookup']
DEFAULT_VAULT_PASSWORD_FILE(/home/tansper/ansible/ansible.cfg) = /home/tansper/ansible/scripts/vault_password.sh
EDITOR(env: EDITOR) = vim
HOST_KEY_CHECKING(/home/tansper/ansible/ansible.cfg) = False
PAGER(env: PAGER) = less
PERSISTENT_COMMAND_TIMEOUT(/home/tansper/ansible/ansible.cfg) = 240
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/tansper/ansible/ansible.cfg) = 30
PERSISTENT_CONNECT_TIMEOUT(/home/tansper/ansible/ansible.cfg) = 240
RETRY_FILES_ENABLED(/home/tansper/ansible/ansible.cfg) = True
```

### Steps to Reproduce

1. use sonic_stp module with the replaced option
2. use this config and run it multiple times and each time try to add or remove a new vlan to/from and STP instance.
```
    "sonic__stp": {
        "global": {
            "bpdu_filter": true,
            "bridge_priority": 4096,
            "enabled_protocol": "mst",
            "loop_guard": true
        },
        "mstp": {
            "mst_instances": [
                {
                    "bridge_priority": 4096,
                    "mst_id": 0
                },
                {
                    "bridge_priority": 4096,
                    "mst_id": 1,
                    "vlans": [
                        "20",
                        "90"
                    ]
                },
                {
                    "bridge_priority": 4096,
                    "mst_id": 2,
                    "vlans": [
                        "14",
                        "22",
                        "70",
                        "72",
                        "91"
                    ]
                },
                {
                    "bridge_priority": 4096,
                    "mst_id": 3,
                    "vlans": [
                        "21",
                        "23",
                        "69",
                        "71",
                        "78",
                        "92"
                    ]
                },
                {
                    "bridge_priority": 4096,
                    "mst_id": 15,
                    "vlans": [
                        "3000"
                    ]
                }
            ],
            "mst_name": "redacted",
            "revision": 12
        }
    }
```

### Expected Behavior

It adds the new VLAN to the MST instance along with the previously defined VLAN-s. 

### Actual Behavior

It removes the previous VLAN-s defined in the STP instance.

### Logs

```

TASK [dell_sonic : Merge STP configuration for Dell Sonic] *********************************************************************************************************************************************************************************************************************************
*** before
--- after
***************
*** 224,233 ****
                  'bridge_priority': 4096,
                  'mst_id': 2,
                  'vlans': [
!                     '22',
!                     '70',
!                     '72',
!                     '91'
                  ]
              },
              {
--- 224,230 ----
                  'bridge_priority': 4096,
                  'mst_id': 2,
                  'vlans': [
!                     '14'
                  ]
              },
              {
changed: [REDACTED]
*** before
--- after
***************
*** 224,233 ****
                  'bridge_priority': 4096,
                  'mst_id': 2,
                  'vlans': [
!                     '22',
!                     '70',
!                     '72',
!                     '91'
                  ]
              },
              {
--- 224,230 ----
                  'bridge_priority': 4096,
                  'mst_id': 2,
                  'vlans': [
!                     '14'
                  ]
              },
              {
```

Rerunning the same task reverts it for some reason?

```

TASK [dell_sonic : Merge STP configuration for Dell Sonic] *********************************************************************************************************************************************************************************************************************************
*** before
--- after
***************
*** 224,230 ****
                  'bridge_priority': 4096,
                  'mst_id': 2,
                  'vlans': [
!                     '14'
                  ]
              },
              {
--- 224,233 ----
                  'bridge_priority': 4096,
                  'mst_id': 2,
                  'vlans': [
!                     '22',
!                     '70',
!                     '72',
!                     '91'
                  ]
              },
              {
changed: [REDACTED]
*** before
--- after
***************
*** 224,230 ****
                  'bridge_priority': 4096,
                  'mst_id': 2,
                  'vlans': [
!                     '14'
                  ]
              },
              {
--- 224,233 ----
                  'bridge_priority': 4096,
                  'mst_id': 2,
                  'vlans': [
!                     '22',
!                     '70',
!                     '72',
!                     '91'
                  ]
              },
              {
```

**Comment by TafkaMax** [comment]
> For this module, this is correct behavior. Replaced state is implemented at a dictionary granularity. The replaced you specified in the playbook deletes the existing configuration for the mst_id 2 instance dictionary and replaces it with the new configuration for the mst_id 2 instance dictionary that you specified in the playbook. Use merged state to add a vlan item to the list of vlans of an mst instance.  
> 
> Overridden state will delete the existing STP configuration and override it with the STP configuration specified in the playbook.

Ok, thanks! Closing this task.

**Comment by TafkaMax** [comment]
I have to reopen this issue. I have had multiple times now that using either replaced or overridden my whole MSTP config gets wiped.

I will try to use merged right now.

**Comment by TafkaMax** [comment]
> [@TafkaMax](https://github.com/TafkaMax) It sounds like you are not clear on how overridden and replaced state works. Can you describe what you are trying to configure?

I added new VLAN-s to my MSTP spanning tree instances. In both cases using overriden and replaced, what happened was that all of my STP instances were removed. After rerunning the playbook they were again readded. After running the playbook again, they were removed, like it was in a loop.

Using `merged` has the drawback that it will not remove the spanning-trees that I have not defined, it will merge them, that is why I wished to use either replaced or overridden, but using them made the ansible unstable and not idempotent for me.

**Comment by TafkaMax** [comment]
Like this:

```yaml
---
- name: Merge STP configuration for Dell Sonic
  dellemc.enterprise_sonic.sonic_stp:
    config: '{{ sonic__stp }}'
    state: merged
```

```yaml
sonic__stp:
  global:
    enabled_protocol: mst
    loop_guard: true
    bpdu_filter: true
    bridge_priority: 4096
  mstp:
    mst_name: example
    revision: 1
    mst_instances:
      - mst_id: 0
        bridge_priority: 4096
      - mst_id: 1
        bridge_priority: 4096
        vlans:
          - '2'
          - '3'
      - mst_id: 2
        bridge_priority: 4096
        vlans:
          - '4'
          - '5'
          - '6'
      - mst_id: 3
        bridge_priority: 4096
        vlans:
          - '7'
          - '8'
          - '9'
          - '10'
          - '11'
          - '12'
          - '13'
          - '14'
          - '15'
          - '16'
          - '17'
          - '18'
      - mst_id: 15
        bridge_priority: 4096
        vlans:
          - '100'
```
