### ISSUE TITLE
[FEATURE]: Enable and configure SAG

### ISSUE THREAD

**Issue by fzakfeld** [ansible-collections/dellemc.enterprise_sonic#514]
**Describe the solution you'd like**
I'd like to have the option to enable and configure SAG, including IPv4 and IPv6 anycast adresses.

**Describe alternatives you've considered**
Use RESTCONF
```
- name: Configure SAG
  dellemc.enterprise_sonic.sonic_api:
    url: data/sonic-sag:sonic-sag
    method: "PATCH"
    body:
      sonic-sag:sonic-sag:
        SAG:
          SAG_LIST: "{{ sonic_sag_list }}"
        SAG_GLOBAL:
          SAG_GLOBAL_LIST:
            - IPv4: enable
              IPv6: enable
              gwmac: "{{ sonic_sag_virtual_mac }}"
              table_distinguisher: IP
    status_code: 204
  when: sonic_sag_enabled
  notify: Write sonic restconf config
```
**Additional context**
`sonic_l3_interfaces` supports setting IPv4 anycast addresses but not IPv6, and enabling SAG is not supported at all.

**Community Note**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
