### ISSUE TITLE
[FEATURE]: Make "system-mac" configurable in "dellemc.enterprise_sonic.sonic_lag_interfaces"

### ISSUE THREAD

**Issue by benedikt97** [ansible-collections/dellemc.enterprise_sonic#517]
When using EVPN-Multihoming it is needed to set a "system-mac" on a per PortChannel basis, especially when using the "evpn ethernet segment auto-system-mac" function. A working config would look like:

```
!
interface PortChannel5
 switchport access Vlan 10
 no shutdown
 system-mac 02:01:01:01:01:01
 !
 evpn ethernet-segment auto-system-mac
 !
```
The ESI is created out of the system_mac, so the system_mac needs to be unique for every switch combinations which share ethernet segments. 

The current "dellemc.enterprise_sonic.sonic_lag_interfaces" lacks this option. It is possible to set the esi, but not the system_mac.

```
- name: Create PortChannel5
  connection: httpapi
  dellemc.enterprise_sonic.sonic_lag_interfaces:
    config:
     - name: PortChannel5
       members:
         interfaces:
           - member: Eth1/5
       ethernet_segment:
         esi_type: auto_lacp
         esi: AUTO
        _system_mac: "02:02:01:01:01:01"_
```

But maybe im just not able to find it in the documentation.
