### ISSUE TITLE
No --diff output from network resource modules

### ISSUE THREAD

**Issue by dataolle** [ansible-collections/dellemc.enterprise_sonic#57]
##### SUMMARY

Implement "--diff" output in network resource modules such as sonic_interfaces, sonic_vlans etc etc.
This works with other vendors network resource modules, and also dellemc.os10 implements diff output.
I see the data is there when running in verbose mode (before and after) so i guess the data for ansible-playbook to display the diff is not implemented in the dellemc.enterprise_sonic network resource modules.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

implement diff mode for sonic network resource modules.

##### ADDITIONAL INFORMATION

It would be grate for sanity check in combination with "check mode" to see what effective changes to a device will be compared to the current running configuration.

```yaml
- hosts: all
  connection: httpapi
  gather_facts: true
  collections:
    - dellemc.enterprise_sonic

  tasks:
    - name: Create Interfaces
      sonic_interfaces:
        config: '{{sonic_interfaces}}'
      when: sonic_interfaces is defined and sonic_interfaces
```

Using this variable data:
```yaml
sonic_interfaces:
  - description: '"MCLAG to LEAF-2 Eth1/51"'
    enabled: true
    name: Eth1/51
```
Run this command
```console
ansible-playbook -i inventory.yaml playbook.yaml
```
Change variable to this
```yaml
sonic_interfaces:
  - description: '"MCLAG to LEAF-4 Eth1/51"'
    enabled: true
    name: Eth1/51
```
And run this:
```console
ansible-playbook -i inventory.yaml playbook.yaml --check --diff
```
I would expact to return the diff (interface description for Eth1/51).
This is what happens with other network resource modules and i would expect the enterprise sonic ones to do the same.
