### ISSUE TITLE
Add ability to specify VLAN description/name

### ISSUE THREAD

**Issue by zhouska** [ansible-collections/dellemc.enterprise_sonic#93]
##### SUMMARY
VLAN description/name is a pretty basic idea and SONIC supports it in the CLI.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
sonic_vlans

##### ADDITIONAL INFORMATION
Something like this:

```yaml
sonic_vlans:
      config:
          - vlan_id: 2
            description: "Internal"
        state: merged
```
