### ISSUE TITLE
sonic_l2_interfaces error "code": -32603,

### ISSUE THREAD

**Issue by ldurbanredhat** [ansible-collections/dellemc.enterprise_sonic#94]
##### SUMMARY

I'm running ansible automation platform 2.0 using automation controller 4.0. I'm trying to use the dellemc.enterprise collection and the dellemc.enterprise_sonic.sonic_l2_interfaces and it is not assigning ports to existing vlan

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

dellemc.enterprise_sonic.sonic_l2_interfaces

##### ANSIBLE VERSION

```paste below

ansible [core 2.12.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True

```

##### COLLECTION VERSION

```paste below
Name                       Version       Shadowed  Type       Path                                                                              
 0│ansible.builtin            2.12.5.post0  False     contained  /usr/local/lib/python3.8/site-packages/ansible                                    
 1│ansible.controller         4.2.0         False     contained  /usr/share/ansible/collections/ansible_collections/ansible/controller             
 2│ansible.netcommon          3.0.1         False     contained  /usr/share/ansible/collections/ansible_collections/ansible/netcommon              
 3│ansible.posix              1.4.0         False     contained  /usr/share/ansible/collections/ansible_collections/ansible/posix                  
 4│ansible.utils              2.6.1         False     contained  /usr/share/ansible/collections/ansible_collections/ansible/utils                  
 5│community.general          5.1.0         False     contained  /usr/share/ansible/collections/ansible_collections/community/general              
 6│community.vmware           2.6.0         False     contained  /usr/share/ansible/collections/ansible_collections/community/vmware               
 7│dellemc.enterprise_sonic   1.1.0         False     contained  /usr/share/ansible/collections/ansible_collections/dellemc/enterprise_sonic       
 8│dellemc.openmanage         5.4.0         False     contained  /usr/share/ansible/collections/ansible_collections/dellemc/openmanage             
 9│dellemc.os10               1.1.1         False     contained  /usr/share/ansible/collections/ansible_collections/dellemc/os10                   
10│dellemc.powerflex          1.2.0         False     contained  /usr/share/ansible/collections/ansible_collections/dellemc/powerflex              
11│redhat.rhel_idm            1.7.0         False     contained  /usr/share/ansible/collections/ansible_collections/redhat/rhel_idm
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

z9100-02# show version

Software Version  : '4.0.0-Enterprise_Advanced'
Product           : Enterprise SONiC Distribution by Dell Technologies
Distribution      : '10.12'
Kernel            : '4.19.0-9-2-amd64'
Config DB Version : version_4_0_1
Build Commit      : 'cfcae285b'
Build Date        : Fri Apr 22 23:39:23 UTC 2022
Built By          : 
Platform          : x86_64-dell_z9100_c2538-r0
HwSKU             : Force10-Z9100-C32
ASIC              : broadcom
Hardware Version  : A00
Serial Number     : 
Uptime            : 14:37:52 up 27 days, 1:26, 1 user, load average: 2.31, 1.99, 1.77
Mfg               : DELL

##### STEPS TO REPRODUCE

```yaml
---
# host_vars file
hostname: z9100-01
ansible_network_os: dellemc.enterprise_sonic.sonic

# Additional parameters for connection type httpapi:
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false

---
# playbook
- name: Dell VLAN Management Demo
  hosts: dell_demo
  gather_facts: false
  connection: httpapi

  collections:
    - dellemc.enterprise_sonic
  
  tasks:
- name: Configure switch port of interfaces
  dellemc.enterprise_sonic.sonic_l2_interfaces:
    config:
     - name: Eth1/1/1
       access:
         vlan: 12
       trunk:
         allowed_vlans:
            - vlan: 13
            - vlan: 14
    state: merged
```

##### Before state:
 -------------

do show Vlan
Q: A - Access (Untagged), T - Tagged
NUM        Status      Q Ports
10         Inactive
11         Inactive
12         Inactive    A  Eth1/4
13         Inactive    T  Eth1/4
14         Inactive    A  Eth1/5
15         Inactive    T  Eth1/5

##### Run Playbook:
 ------------

```yaml
- name: Configure switch port of interfaces
  dellemc.enterprise_sonic.sonic_l2_interfaces:
    config:
     - name: Eth1/1/1
       access:
         vlan: 12
       trunk:
         allowed_vlans:
            - vlan: 13
            - vlan: 14
    state: merged
```

##### After state:
 ------------

do show Vlan
Q: A - Access (Untagged), T - Tagged
NUM        Status      Q Ports
10         Inactive
11         Inactive
12         Inactive    A  Eth1/1/1
                       A  Eth1/4
13         Inactive    T  Eth1/1/1
                       T  Eth1/4
14         Inactive    A  Eth1/1/1
                       A  Eth1/5
15         Inactive    T  Eth1/5

##### ACTUAL RESULTS

{
  "code": -32603,
  "msg": "{'ietf-restconf:errors': {'error': [{'error-type': 'protocol', 'error-tag': 'invalid-value', 'error-message': 'Not Found'}]}, 'code': 404, 'request_data': {'path': 'data/openconfig-interfaces:interfaces/interface=Eth1%2f1/1/openconfig-if-ethernet:ethernet/openconfig-vlan:switched-vlan/config', 'method': 'PATCH'}}",
  "exception": "  File \"/usr/share/ansible/collections/ansible_collections/dellemc/enterprise_sonic/plugins/module_utils/network/sonic/config/l2_interfaces/l2_interfaces.py\", line 103, in execute_module\n    edit_config(self._module, to_request(self._module, requests))\n  File \"/usr/share/ansible/collections/ansible_collections/dellemc/enterprise_sonic/plugins/module_utils/network/sonic/sonic.py\", line 140, in edit_config\n    return connection.edit_config(commands)\n  File \"/usr/local/lib/python3.8/site-packages/ansible/module_utils/connection.py\", line 200, in __rpc__\n    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)\n",
  "invocation": {
    "module_args": {
      "config": [
        {
          "name": "Eth1/1/1",
          "access": {
            "vlan": 42
          },
          "trunk": {
            "allowed_vlans": [
              {
                "vlan": 10
              }
            ]
          }
        }
      ],
      "state": "merged"
    }
  },
  "_ansible_no_log": false,
  "changed": false

```paste below

```
